DROP TABLE IF EXISTS stats cascade;

CREATE TABLE IF NOT EXISTS stats (
id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
app VARCHAR(30) NOT NULL,
ip VARCHAR(50) NOT NULL,
uri VARCHAR(250) NOT NULL,
timestamp TIMESTAMP WITHOUT TIME ZONE,
CONSTRAINT pk_stats PRIMARY KEY (id)
);